site_name: Arend
site_url: http://arend.top/
site_description: Arend is good at maths. You aren’t.

repo_url: https://github.com/valis/vclang
edit_uri: edit/master/docs/

pages:
    - Overview: index.md
    - Tutorial: tutorial.md
    - Language Reference:
        - Definitions: language-reference/definitions.md

theme: readthedocs

# Code highlighting
# highlight.js is built from https://github.com/kirelagin/highlight.js/tree/arend
theme_dir: docs/highlight/theme/

site_dir: build/site/

markdown_extensions:
    - toc:
        permalink: True
    - fenced_code
